### ISSUE TITLE
[WIN] 0.4.0 installer fails at .qt-post-link.bat

### ISSUE THREAD

**Issue by stuart-cls** [Quasars/quasar#5] opened 2019-05-29 17:35 UTC
Hi Marko,

The 0.4.0 installer is failing for me. First, like in #2 I had to completly delete the old installation. And now the installer is failing while running `.qt-post-link.bat`. I'm not sure where to start troubleshooting.

Errors:
```
Creating an new conda env in "C:\Users\reads\AppData\Local\Quasar"
...
Installing: qt-5.6.2-vc14h6f8c307_12.tar.bz2
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package '<unknown>::qt-5.6.2-vc14h6f8c307_12'.
LinkError: post-link script failed for package <unknown>::qt-5.6.2-vc14h6f8c307_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\reads\AppData\Local\Quasar\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

failed
ERROR conda.core.link:_execute(568): An error occurred while installing package '<unknown>::qt-5.6.2-vc14h6f8c307_12'.
LinkError: post-link script failed for package <unknown>::qt-5.6.2-vc14h6f8c307_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\reads\AppData\Local\Quasar\Scripts\.qt-post-link.bat
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: ...working... done

LinkError: post-link script failed for package <unknown>::qt-5.6.2-vc14h6f8c307_12
running your command again with `-v` will provide additional information
location of failed script: C:\Users\reads\AppData\Local\Quasar\Scripts\.qt-post-link.bat
==> script messages <==
<None>


"conda" command exited with 1. Cannot continue.

**Comment by markotoplak** [comment] 2019-05-30 05:53
Is it failing on all computers? Are there any particularities you know of? Win 7 or Win 10?

What is the md5sum of you downloaded file?

This is a duplicate of biolab/orange3#3819. Could you try Ales's suggestions?

**Comment by stuart-cls** [comment] 2019-05-30 17:43
So far it's only failing on my main development machine (Win 10), I was able to install it after properly uninstalling 0.3.0 on another Win 10 machine. Besides being my development machine and all the random installs that go along with that, I also have two installations of miniconda on this machine: 64 and 32 bit. However, the Orange installer has always properly chosen the 64-bit as far as I can tell.
I also manually deleted the Quasar-0.3.0 installation instead of using the uninstaller (perhaps unwisely) when I got the binary-compat error.

MD5 is `4e3d45cbe2b9262f2f2b7e9fe00c3201`

The `Orange-3.22.0.dev0+73d93ee` installer with qt-5.9.7 you sent me fails in the same way.

`conda clean --all` deleted a ton of stuff but I still get the error.

I'll add my conda info to the other issue.

**Comment by Guillaumes33** [comment] 2019-06-13 11:36
I found that using the 0.3.2 Quasar Miniconda installer does still work for me.

**Comment by Guillaumes33** [comment] 2019-06-14 11:51
Somewhat related issue. I have 0.3.2 installed, and it won't let me install 0.4.0 now. I get this error. The only thing in the folder is what came with 0.3.2.
![0 4 install error](https://user-images.githubusercontent.com/50418145/59507518-cb0e0900-8e85-11e9-9e03-d233cbfeb151.png)

**Comment by markotoplak** [comment] 2019-06-14 13:07
@Guillaumes33, thank you. Please uninstall 0.3.2 first before installing 0.4.0. 

This is bug biolab/orange3#3830

**Comment by markotoplak** [comment] 2019-06-28 08:49
The problem by @stuart-cls is fixed in today's release. Reusing the same environment is still a problem (see #3830).

**Closed by markotoplak** 2019-06-28 08:49 UTC
